BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 3e-4
  MODEL_FILE_NAME: UBFC_UBFC_UBFC_RhythmMamba_DoiTenLai
  AUG: 1
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: True                # Đổi thành True cho lần chạy đầu tiên để tạo cache
    DATA_FORMAT: NDCHW
    DATA_PATH: "./data/UBFC-rPPG/"     # Cập nhật đường dẫn Raw dataset
    CACHED_PATH: "./data/cached/UBFC/" # Cập nhật đường dẫn lưu dataset sau khi xử lý
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.72
    PREPROCESS :
      DATA_TYPE: [ 'Standardized' ]
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    
      RESIZE:
        H: 128
        W: 128
VALID:
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: True                # Đổi thành True cho lần chạy đầu tiên để tạo cache
    DATA_FORMAT: NDCHW
    DATA_PATH: "./data/UBFC-rPPG/"     # Cập nhật đường dẫn Raw dataset
    CACHED_PATH: "./data/cached/UBFC/" # Cập nhật đường dẫn lưu cache
    EXP_DATA_NAME: ""
    BEGIN: 0.72
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Standardized' ]
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    
      RESIZE:
        H: 128
        W: 128
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson','SNR']
  USE_LAST_EPOCH: True                 # Bài báo RhythmMamba dùng epoch cuối do UBFC không có tập valid thực sự
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: True                # Đổi thành True
    DATA_FORMAT: NDCHW
    DATA_PATH: "./data/UBFC-rPPG/"     # Cập nhật đường dẫn Raw dataset
    CACHED_PATH: "./data/cached/UBFC/" # Cập nhật đường dẫn lưu cache
    EXP_DATA_NAME: ""
    BEGIN: 0.72
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Standardized' ]
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 128
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    
      RESIZE:
        H: 128
        W: 128
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: RhythmMamba
  MODEL_DIR: "./PreTrainedModels"
INFERENCE:
  BATCH_SIZE: 2
  EVALUATION_METHOD: "FFT"        
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: False        
    WINDOW_SIZE: 10        
  MODEL_PATH:   ""